### PR TITLE
[Choreo] Fix intelligent routing availability after deleting and re-creating an API

### PR DESCRIPTION
**Pull request by chathuranga95**
### Purpose
This PR,
- Removes unwanted minor version based intelligent routing regex building for the envoy router
- Fixes a bug where the vhost is neglected on API undeployment

### Issues
Addresses: https://github.com/wso2-enterprise/choreo/issues/28419

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

OS: Mac 14.3
Go: 1.22.1
Java: 11.0.19

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20240514.28

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240514.28

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20240514.28

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240514.28

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240516.1

**Comment by choreo-cicd** [comment]
[] Dataplane(CDP2-WU2) cluster : stage-deployment-v2 : 20240516.2

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : stage-deployment-v2 : 20240516.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20240517.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20240517.2

**Comment by choreo-cicd** [comment]
[canceled] Dataplane(EastUS) cluster : prod-deployment-v2 : 20240517.2

**Comment by choreo-cicd** [comment]
[canceled] Dataplane(EastUS) cluster : prod-deployment-v2 : 20240517.2

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20240517.3

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20240517.3

**Comment by choreo-cicd** [comment]
[] Dataplane(CDP2-WU2) cluster : prod-deployment-v2 : 20240517.3

**Comment by choreo-cicd** [comment]
[] Dataplane(CDP2-WU2) cluster : prod-deployment-v2 : 20240517.3

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : prod-deployment-v2 : 20240517.3

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : prod-deployment-v2 : 20240517.3

**Pull request merged**
