### PR TITLE
Open API Definition for Interceptor and sample interceptor service in Ballerina

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose
- Add the Open API Definition for Interceptor Services.
- Sample interceptor service in Ballerina builds with the Open API Definition.
- Add sample backend for interceptor sample demo.
- Docker-Compose file with backend + interceptor services that connect to the same network of CC with docker compose.

### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2358

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: N/A

### Tested environments

Docker Desktop

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211115.4

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211115.12

**Comment by choreo-cicd** [comment]
[failed] stage-deployment : 20211117.2

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211117.3

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211119.1

**Pull request merged**
