### PR TITLE
Remove feature flag - ROUTER_GRACEFUL_SHUTDOWN_ENABLED

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose
$subject

### Issues

Fixes 

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Comment by renuka-fernando** [comment]
Issue: wso2-enterprise/choreo#28513

**Review by Thushani-Jayasekera — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Review by malinthaprasan — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240715.25

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240715.25

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240715.26

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240715.26

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240715.27

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240715.28

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CDP2-WU2) cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20240718.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20240718.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CDP2-WU2) cluster : prod-deployment-v2 : 20240718.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20240718.1

**Pull request merged**
