### PR TITLE
Dependency version upgrades

### PR DESCRIPTION
**Pull request by Amila-Rukshan**
### Purpose
golang.org/x/net updated - v0.0.0-20220909164309-bea034e7d591
grpc health probe version - 0.4.12

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

OS: Darwin
Env: Docker

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Comment by pubudu538** [comment]
Can you resolve the conflicts? @Amila-Rukshan

**Review by VirajSalaka — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20221019.10

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20221019.10

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20221019.10

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20221019.10

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20221019.10

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20221019.11

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20221019.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20221019.2

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20221021.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : prod-deployment-v2 : 20221021.7

**Pull request merged**
