### PR TITLE
Merge envInfo by deployed revision

### PR DESCRIPTION
**Pull request by ruwiniwj**
### Purpose

Merge the deployment details so that there will only be a single entry per revision with all deployed environments listed in `envInfo`

### Issues

Fixes https://github.com/wso2-enterprise/choreo/issues/17948

### Automation tests
 - Unit tests added: Yes
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [ ] Assigned the project
- [x] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Comment by ruwiniwj** [comment]
Control plane PRs:
- https://github.com/wso2-enterprise/choreo-cp-env-overlay/pull/6476
- https://github.com/wso2-enterprise/choreo-cp-env-overlay/pull/6475
- https://github.com/wso2-enterprise/choreo-cp-env-overlay/pull/6477

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230126.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20230126.4

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230126.4

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230127.1

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230127.1

**Pull request merged**
