### PR TITLE
bug fix: Override hostname is not properly replaced. Hence GA connection fails

### LINKED ISSUE #2414: Adapter readiness probe fails as connection with Global Adapter fails.
### Description:
$subject. This was due to the configuration refactor implementation [1] . The Overwritehostname is not replaced with OverrideHostName property in the implementation.

[1] https://github.com/wso2/product-microgateway/issues/2300

### Steps to reproduce:
Run the adapter with global-adapter with no OverwriteHostName property. 

### Affected Product Version:
Choreo-Connect-1.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
$subject. 

### Issues

Fixes #2414 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211123.7

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211123.11

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211124.2

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211124.2

**Pull request merged**
