### PR TITLE
Sample interceptor service implementations with mTLS - Java, NodeJS, Golang

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose
Sample interceptor service implementations with mTLS

### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2405
Fixes https://github.com/wso2/product-microgateway/issues/2393

TODO:
- Push docker images of sample services after merging the PR
- Update the docs-apim with samples

The PR contains many auto-generated codes and only updated license headers where the interceptor logic took place.

Relevant folk repo readme content: https://github.com/renuka-fernando/product-microgateway/tree/interceptor-samples/samples/interceptors

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: N/A

### Tested environments

Docker Compose

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by pubudu538** [comment]
What is the possibility of pushing a node js module?

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211123.7

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211123.11

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211124.2

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211124.2

**Pull request merged**
