### PR TITLE
Update choreo branch after 1.0.0 alpha

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose

$subject
### Issues

Task

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: N/A

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [-] Validated respective github issues
- [-] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211115.4

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211115.12

**Comment by renuka-fernando** [comment]
- [x] Tested with already existing API
- [x] Tested create new revision and Deploy

**Comment by choreo-cicd** [comment]
[failed] stage-deployment : 20211117.2

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211117.3

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211119.1

**Pull request merged**
