### PR TITLE
[Choreo] Update rate-limiter to the latest version

### PR DESCRIPTION
**Pull request by slahirucd7**
$subject

### Issues

Fixes #
Relates to: https://github.com/wso2-enterprise/choreo/issues/26811

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20240318.16

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240318.16

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20240318.16

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240318.16

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20240319.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240319.2

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20240319.2

**Comment by choreo-cicd** [comment]
[canceled] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240319.2

**Comment by choreo-cicd** [comment]
[]  : stage-deployment-v2 : 20240319.4

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240319.4

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : stage-deployment-v2 : 20240319.4

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240319.4

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20240320.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20240320.3

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20240320.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20240320.3

**Pull request merged**
