### PR TITLE
Forward the authorization header to backend if the authentication is disabled at the gateway level

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Issues

Related to #3139 

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments

Tested on docker

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — DISMISSED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20221112.1

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20221112.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20221112.1

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20221112.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20221117.2

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : stage-deployment-v2 : 20221117.2

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20221121.5

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20221121.5

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20221121.5

**Pull request merged**
