### PR TITLE
Adding apiUUID List to API ReFetching

### PR DESCRIPTION
**Pull request by rashm1n**
### Purpose
$Subject

### Issues

Fixes
* https://github.com/wso2-enterprise/choreo/issues/24460

### Automation tests
 - Unit tests added: No
 - Integration tests added: No
---

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Review by malinthaprasan — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : dev-deployment-v2 : 20231016.14

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20231016.14

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20231016.14

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20231016.14

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20231016.38

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20231016.38

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : prod-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231017.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20231017.2

**Pull request merged**
