### PR TITLE
[Choreo][xDS]: Log improvement to track request type in enforcer callbacks

### PR DESCRIPTION
**Pull request by NomadXD**
Signed-off-by: Lahiru De Silva <lahirude@wso2.com>

### Purpose
Log improvement to track request type in enforcer callbacks

### Issues

Related to # https://github.com/wso2-enterprise/choreo/issues/17448
### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [ ] Assigned the project
- [x] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230126.16

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230126.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20230126.4

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230126.4

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230127.1

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230127.1

**Pull request merged**
