### PR TITLE
Bump golang.org/x/net from 0.4.0 to 0.7.0

### PR DESCRIPTION
**Pull request by VajiraPrabuddhaka**
### Purpose
$subject

Related PR : https://github.com/wso2/product-microgateway/pull/3257

### Issues

Fixes #

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20230321.28

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230321.28

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230322.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(CentralIN) cluster : stage-deployment-v2 : 20230322.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230322.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230322.4

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CentralIN) cluster : stage-deployment-v2 : 20230322.4

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230322.4

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230322.4

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20230327.5

**Comment by choreo-cicd** [comment]
[failed] Dataplane(CentralIN) cluster : prod-deployment-v2 : 20230327.5

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230327.7

**Pull request merged**
