### PR TITLE
Run `go mod tidy` after asb-sdk upgrade

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

$subject to fix a build failure in #2691 
### Issues

Task

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20220301.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20220301.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20220302.3

**Pull request merged**
