### PR TITLE
[choreo] Base images and dependency version upgrades

### PR DESCRIPTION
**Pull request by slahirucd7**
### Purpose
Upgrades base images in the Adapter and Enforcer and dependency versions to the latest versions.

### Issues

Fixes #
https://github.com/wso2/product-microgateway/issues/3195
https://github.com/wso2/product-microgateway/issues/3186
https://github.com/wso2/product-microgateway/issues/3190
https://github.com/wso2/product-microgateway/issues/3232

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20230209.10

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230209.11

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230209.11

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230209.11

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230210.2

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20230210.2

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230210.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230210.4

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230210.4

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230210.5

**Pull request merged**
