### PR TITLE
Fixing consul service mesh issues

### PR DESCRIPTION
**Pull request by pubudu538**
### Purpose
Fixed the following issues identified in Consul service discovery.

1. ACL token not used properly
2. Certs are missing when working with Consul service mesh

### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2409

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Comment by pubudu538** [comment]
Have to use ACLToken as the key and could not use aclToken as it gives a lint error.

**Review by VirajSalaka — APPROVED** [review]

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211123.7

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211123.11

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211124.2

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211124.2

**Pull request merged**
