### PR TITLE
Improve interceptor extension

### PR DESCRIPTION
**Pull request by AmaliMatharaarachchi**
### Purpose

support `serviceURL` option and remove host, port, scheme
```
x-wso2-request-interceptor:
  serviceURL: https://xml-interceptor:9081
  includes:
    - request_body
```

### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2417

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes (existing tests covers the changes)

### Tested environments

Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by renuka-fernando** [comment]
Updated docs with https://github.com/wso2/docs-apim/pull/4953

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211123.7

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211123.11

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211124.2

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211124.2

**Pull request merged**
