### PR TITLE
Access log api UUID from enforcer

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose
$subject

Remove printing RouteName as it is not printed when Rate Limited, Ext auth failed or CORS are handled. Hence using Ext Auth dynamic metadata.

- Upstream
choreo-connect-router-1        | [2023-07-26T05:51:12.279Z]' 'localhost:9095' 'run.mocky.io' 'GET' '/v2/pet/findByStatus?status=pending' '/v3/9ec5a57e-733c-4338-9854-7ea31866dcba/pet/findByStatus?status=pending' 'HTTP/1.1' '200' 'via_upstream' '-' 'curl/7.79.1' '019f09e4-95ea-47dc-a16d-0dd6ac775251' '-' '185.42.117.109:443' '0' '31' '823' '-' '666' '0' '3' '823' '648957e7a675c35145393369' '-' '

- Rate Limited
choreo-connect-router-1        | [2023-07-26T05:51:20.161Z]' 'localhost:9095' 'localhost:9095' 'GET' '/v2/pet/findByStatus?status=pending' '/v2/pet/findByStatus?status=pending' 'HTTP/1.1' '429' 'request_rate_limited' 'RL' 'curl/7.79.1' '1ee481aa-6581-41df-b1fc-4cc13c7c374b' '-' '-' '0' '121' '35' '-' '-' '-' '0' '-' '648957e7a675c35145393369' '-' '

- Auth Failure
choreo-connect-router-1        | [2023-07-26T05:51:56.848Z]' 'localhost:9095' 'localhost:9095' 'GET' '/v2/pet/findByStatus?status=pending' '/v2/pet/findByStatus?status=pending' 'HTTP/1.1' '401' 'ext_authz_denied' 'UAEX' 'curl/7.79.1' '34fb64d0-ba61-4827-ada1-ecae4a418b77' '-' '-' '0' '138' '36' '-' '-' '-' '0' '-' '648957e7a675c35145393369' '-' '

- CORS success
choreo-connect-router-1        | [2023-07-26T05:51:25.998Z]' '-' 'localhost:9095' 'OPTIONS' '-' '/v2/pet/findByStatus?status=pending' 'HTTP/1.1' '200' 'cors_response' '-' 'curl/7.79.1' 'f142fd7b-8511-4b8c-bff9-cbf0b5740820' '-' '-' '0' '0' '1' '-' '-' '-' '0' '-' '-' '-' '

- CORS failure
choreo-connect-router-1        | [2023-07-26T05:51:38.695Z]' 'localhost:9095' 'localhost:9095' 'OPTIONS' '/v2/pet/findByStatus?status=pending' '/v2/pet/findByStatus?status=pending' 'HTTP/1.1' '204' 'ext_authz_denied' 'UAEX' 'curl/7.79.1' '74e7e2ba-1059-41c7-9ce9-66cdb37da525' '-' '-' '0' '0' '56' '-' '-' '-' '0' '-' '648957e7a675c35145393369' 'CORS_FAILURE' '

### Issues

Fixes #

### Automation tests
 - Unit tests added: No
 - Integration tests added:No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [X] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20230726.15

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20230726.15

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230727.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230727.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230727.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230727.3

**Pull request merged**
