### PR TITLE
Migrate ASB client to azure-sdk-for-go

### LINKED ISSUE #2477: Azure service bus go client is updated to a newer library and need to move to that asap
### Describe your problem(s)
Current used client library [1] has archived by the team (2021-11-12) and they are now recommending to migrate to new one [2] which as I have checked has api changes. See migration guide [3]

[1] https://github.com/Azure/azure-service-bus-go
[2]https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/README.md
[3]https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md/

### How will you implement it

---

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

Existing client pkg is deprecated by it's developers. Therefore migrating the ASB client to new azure sdk
### Issues

Fixes #2477

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

docker-compose with apim.

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment-v2 : 20220125.15

**Comment by choreo-cicd** [comment]
[failed] dev-deployment-v2 : 20220125.16

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220126.1

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment-v2 : 20220128.1

**Pull request merged**
