### PR TITLE
Updating minimum cpu and memory in cc

### PR DESCRIPTION
**Pull request by pubudu538**
### Purpose

Updating minimum cpu and memory in cc

Update xms/x in enforcer

### Issues

Fixed https://github.com/wso2/product-microgateway/issues/2380

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211115.4

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211115.12

**Comment by choreo-cicd** [comment]
[failed] stage-deployment : 20211117.2

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211117.3

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211119.1

**Pull request merged**
