### PR TITLE
Revert "Remove sandbox cluster creation "

### PR DESCRIPTION
**Pull request by VirajSalaka**
Reverts wso2/product-microgateway#3277

### CODE REVIEW

**Review by menakaj — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230304.2

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230304.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230304.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230307.1

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20230307.3

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230307.3

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230307.3

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230307.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230307.3

**Pull request merged**
