### PR TITLE
Global Adapter Feature

### LINKED ISSUE #2132: Update Local Adapter to communicate with Global adapter
### Describe your problem

Local Adapter needs to be changed to communicate with Global Adapter. 

### Describe your solution

At the Local Adapter startup, API UUID list should be received from the Global Adapter.
Local Adapter needs to fetch the corresponding APIs from the control plane at startup. (using /retrieve-api-artifacts endpoint)
When a API deploy or undeploy event is received from the Local Adapter, Enforcer and Router components need to be updated.

Related Issue: https://github.com/wso2-enterprise/choreo/issues/4333

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose

This PR contains the complete implementation relevant to the Global Adapter Feature. Please note that the  PRs for `feature/global-adapter` branch has already been reviewed.

### Issues

Fixes #2132 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No (Partitioning specific implementation is covered by the integration tests added to the global adapter)

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Comment by VirajSalaka** [comment]
https://github.com/wso2-enterprise/choreo/issues/3930

**Review by praminda — APPROVED** [review]

**Review by Rajith90 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20210825.10

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20210831.1

**Pull request merged**
