### PR TITLE
Update go-control-plane version as v0.10.3 and add rate limit xds files

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose

Signed-off-by: Renuka Fernando <renukapiyumal@gmail.com>

Upgrade go-control-plane version from v0.10.0 to v0.10.3 and add changes done in https://github.com/envoyproxy/go-control-plane/pull/598/files.

The additional changes done in the GCP is related to the rate limit feature.

### Issues

Fixes #

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: N/A

### Tested environments

Tested with apictl + test token
Docker compose

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by AmaliMatharaarachchi — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20221213.14

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20221213.14

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20221213.14

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20221213.14

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20221214.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20221214.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20221214.2

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : prod-deployment-v2 : 20221214.2

**Pull request merged**
