### PR TITLE
Change keyword used in auth

### PR DESCRIPTION
**Pull request by Thushani-Jayasekera**
### Issues

Fixes #

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by slahirucd7 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.6

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241026.6

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241026.6

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.7

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.8

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.9

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.10

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.11

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241026.12

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241028.1

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20241028.1

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241028.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20241029.10

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20241029.10

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20241029.13

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : stage-deployment-v2 : 20241029.13

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : stage-deployment-v2 : 20241029.13

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : prod-deployment-v2 : 20241031.2

**Pull request merged**
