### PR TITLE
[choreo] set the value for auth header from sec-protocol header

### PR DESCRIPTION
**Pull request by Thushani-Jayasekera**
### Purpose

relates to https://github.com/wso2/product-microgateway/pull/3587

### Issues

Fixes #

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241001.21

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241001.22

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241001.22

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241001.22

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241001.23

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241001.23

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241001.23

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20241001.24

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241001.24

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241001.24

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : stage-deployment-v2 : 20241002.4

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241002.7

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20241002.7

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241002.7

**Comment by choreo-cicd** [comment]
[] Dataplane(CDP2-WU2) cluster : prod-deployment-v2 : 20241004.2

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : prod-deployment-v2 : 20241004.2

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : prod-deployment-v2 : 20241004.2

**Comment by choreo-cicd** [comment]
[] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20241004.2

**Pull request merged**
