### PR TITLE
Enable Specifying Upstream Request Timeout at Endpoint Level

### PR DESCRIPTION
**Pull request by SuKSW**
### Purpose
Here the timeout is for the time taken -> from the point where router receives the request from the downstream until the router receives the response from the upstream.

1. Upstream Timeout can be configured in the swagger/OpenAPI definition within the `advanceEndpointConfig` in the respective prod or sandbox extension.
```
 x-wso2-production-endpoints:
    urls:
      - https://localhost:2380/v3
    advanceEndpointConfig:
      timeoutInMillis: 7000
```
2. Also accepts via the APIM UI. In the endpoints tab, when updating settings for the endpoint, the `Duration` set as the `connection timeout` is taken as the upstream request timeout. The `action` for the connection timeout is not considered in CC.

3. The max duration accepted via an API definition can be limited by setting the following param in config.toml
```
[router.upstream.timeouts]
  # Maximum upstream timeout allowed in an OpenAPI definition or API-M UI. 
  # A larger value will be replaced by this.
  maxRouteTimeoutInSeconds = 60
```

### Issues
Closes https://github.com/wso2/product-microgateway/issues/2332

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments
OS name: "linux", arch: "amd64", family: "unix"
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211115.4

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211115.12

**Comment by choreo-cicd** [comment]
[failed] stage-deployment : 20211117.2

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211117.3

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211119.1

**Pull request merged**
