### PR TITLE
Resolve conflicts between master branch and the current branch.

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
Resolve merge conflicts between the master branch and the current branch.

### Issues

#943 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

MacOS
---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Comment by praminda** [comment]
This PR seems to be invalid. Shall we resend the PR will correct diff?

**Comment by praminda** [comment]
This PR seems to be invalid. Shall we resend the PR will correct diff?

**Comment by praminda** [comment]
Please don't remove content from the PR template. Keep empty/default values if you don't need to fill specific sections.

I updated the PR description by adding removed content from the template.

**Comment by VirajSalaka** [comment]
> Please don't remove content from the PR template. Keep empty/default values if you don't need to fill specific sections.
> 
> I updated the PR description by adding removed content from the template.

Ack.

**Pull request merged**
