### PR TITLE
Adding necessary data populations for Moesif Integration

### PR DESCRIPTION
**Pull request by rashm1n**
### Purpose
$Subject

### Issues
* https://github.com/wso2-enterprise/choreo/issues/24711

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20231026.36

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20231026.36

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20231027.2

**Pull request merged**
