### PR TITLE
Upgrade azure-go-sdk

### PR DESCRIPTION
**Pull request by praminda**
### Purpose

This azure-sdk version contains a fix to asb client's reconnect behaviour
### Issues

Related to https://github.com/Azure/azure-sdk-for-go/issues/17017

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment-v2 : 20220223.31

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220228.1

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20220301.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20220301.3

**Pull request merged**
