### PR TITLE
Revert "Updating container base images and maven dependancies"

### PR DESCRIPTION
**Pull request by VirajSalaka**
Reverts wso2/product-microgateway#2899

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by AmaliMatharaarachchi — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20220519.12

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20220519.12

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20220519.12

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20220524.5

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20220526.2

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20220526.2

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20220526.2

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : prod-deployment-v2 : 20220526.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : prod-deployment-v2 : 20220526.4

**Pull request merged**
