### PR TITLE
Incrementing analytics publisher version to 1.2.16

### PR DESCRIPTION
**Pull request by rashm1n**
### Purpose
$Subject

* https://github.com/wso2-enterprise/choreo/issues/25069

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20231108.27

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20231108.27

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20231109.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20231109.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20231109.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231109.4

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20231109.4

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20231109.4

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20231109.4

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20231109.5

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20231109.5

**Pull request merged**
