### PR TITLE
[Choreo] Add branch parameter and refactor the code

### PR DESCRIPTION
**Pull request by shananjana**

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230302.8

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230302.8

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230302.8

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230303.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230303.3

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230303.2

**Pull request merged**
