### PR TITLE
Changing API Context Setting Mechanism in ChoreoFaultAnalyticsProvider

### PR DESCRIPTION
**Pull request by rashm1n**
### Purpose
$Subject

### Issues
* https://github.com/wso2-enterprise/choreo/issues/24711

### CODE REVIEW

**Review by slahirucd7 — APPROVED** [review]

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20231026.36

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20231026.36

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20231027.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20231027.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20231027.2

**Pull request merged**
