### PR TITLE
Remove sandbox cluster creation 

### PR DESCRIPTION
**Pull request by NomadXD**
### Purpose
Remove sandbox cluster creation 

### Issues

Fixes #

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : dev-deployment-v2 : 20230302.23

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20230302.23

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20230302.23

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230303.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230303.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230303.4

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230303.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230303.4

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230303.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230303.2

**Pull request merged**
