### PR TITLE
Make retry condition configurable in Choreo Connect Router.

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Issues

Via this we can switch the conditions for which router would retry the requests. 

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [ ] Assigned 'Type' label
- [ ] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240715.28

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20240715.28

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240715.28

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240715.28

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240715.29

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CDP2-WU2) cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240716.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20240718.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20240718.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CDP2-WU2) cluster : prod-deployment-v2 : 20240718.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20240718.1

**Pull request merged**
