### PR TITLE
[choreo] bug fix: API not deleted with event, when setting xds cache under a common label for dynamic environments

### PR DESCRIPTION
**Pull request by VajiraPrabuddhaka**
### Purpose

- Add missing changes for $subject related to https://github.com/wso2/product-microgateway/pull/3259
- Some refactoring

### Issues

Fixes #

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by RAVEENSR — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230221.23

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230221.23

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230221.23

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230222.1

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20230222.1

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230222.1

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230222.4

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230222.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : prod-deployment-v2 : 20230222.4

**Pull request merged**
