### PR TITLE
Add temporary API Key authenticator impl

### PR DESCRIPTION
**Pull request by mevan-karu**
### Purpose
This PR adds a temporary API key implementation to support new API-Key based authentication mechanism.

### CODE REVIEW

**Review by senthalan — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20241021.13

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20241021.13

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20241021.13

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20241022.3

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20241022.3

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20241022.3

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : stage-deployment-v2 : 20241022.3

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : stage-deployment-v2 : 20241022.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20241022.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20241022.3

**Pull request merged**
