### PR TITLE
update alias name

### PR DESCRIPTION
**Pull request by AmaliMatharaarachchi**
### Purpose

Update alias name from production_endpoint to productionEndpoint and sandbox_endpoint to sandboxEndpoint in environment label specific variable support.

### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2420

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211115.15

**Comment by choreo-cicd** [comment]
[failed] stage-deployment : 20211117.2

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211117.3

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211119.1

**Pull request merged**
