### PR TITLE
Fix intermittent test failures in build pipeline

### PR DESCRIPTION
**Pull request by VirajSalaka**
### Purpose
Fix intermittent test failure due to the order of elements were not guaranteed in the returned deploymentList. Fixes are introduced to the tests.

### Automation tests
 - Unit tests added: Yes
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [ ] Assigned the project
- [x] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by VajiraPrabuddhaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230213.11

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230213.11

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230213.11

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230215.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230215.1

**Pull request merged**
