### PR TITLE
[choreo] Dependency version upgrades

### PR DESCRIPTION
**Pull request by slahirucd7**
### Purpose
Upgrades below dependency versions

- io.netty.version
- jackson.databind.version
- jackson.annotations.version

### Issues

Fixes #

https://github.com/wso2/product-microgateway/issues/3106
https://github.com/wso2/product-microgateway/issues/3094

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[failed] DataplaneE2 cluster : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Pull request merged**
