### PR TITLE
Remove sandbox cluster creation

### PR DESCRIPTION
**Pull request by VirajSalaka**
Reverts wso2/product-microgateway#3291

### CODE REVIEW

**Review by menakaj — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : dev-deployment-v2 : 20230327.20

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20230327.20

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20230327.20

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230327.22

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20230327.22

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20230327.22

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230328.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230328.1

**Comment by choreo-cicd** [comment]
[failed] Dataplane(CentralIN) cluster : stage-deployment-v2 : 20230328.1

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CentralIN) cluster : stage-deployment-v2 : 20230328.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230328.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230328.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20230328.3

**Comment by choreo-cicd** [comment]
[failed] Dataplane(CentralIN) cluster : prod-deployment-v2 : 20230328.3

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : prod-deployment-v2 : 20230328.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(CentralIN) cluster : prod-deployment-v2 : 20230328.4

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20230328.4

**Pull request merged**
