### PR TITLE
Rate limiter health check

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose

$subject

Adapter Log
```log
choreo-connect-adapter-1  | 2023-09-07 05:52:57 INFO [health.go:49] - [health.service.SetStatus] [-] Update health status of service "adapter.internal.RateLimiterGrpcService" as HEALTHY
```

```sh
~ $ sh check_health.sh
status: SERVING
```

### Issues

Fixes #

### Automation tests
 - Unit tests added:No
 - Integration tests added:No

### Tested environments

Tested in Docker Compose - using check_health script

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by slahirucd7 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230907.18

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20230907.18

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20230907.18

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230907.18

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230911.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20230911.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230911.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20230911.2

**Comment by choreo-cicd** [comment]
[failed] Dataplane(EastUS) cluster : stage-deployment-v2 : 20230911.2

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20230911.8

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230911.8

**Pull request merged**
