### PR TITLE
Test dynamic endpoints with custom filters

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose
Test dynamic endpoints with custom filters

### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2378

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: Yes

### Tested environments
Docker Compose

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by pubudu538 — APPROVED** [review]

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211115.4

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211115.12

**Comment by choreo-cicd** [comment]
[failed] stage-deployment : 20211117.2

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211117.3

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211119.1

**Pull request merged**
