### PR TITLE
Prepare for 1.0.0-rc3 release

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose
Prepare for 1.0.0-rc3 release

### Issues

Task

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: N/A

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by praminda — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment-v2 : 20220125.15

**Comment by choreo-cicd** [comment]
[failed] dev-deployment-v2 : 20220125.16

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220126.1

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment-v2 : 20220128.1

**Pull request merged**
