### PR TITLE
Create product-microgateway-sca-scan pipeline in choreo branch

### PR DESCRIPTION
**Pull request by shananjana**

### CODE REVIEW

**Review by pubudu538 — DISMISSED** [review]

**Review by slahirucd7 — APPROVED** [review]

**Review by renuka-fernando — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[failed] DataplaneE2 cluster : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[failed]  : dev-deployment-v2 : 20230120.10

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20230123.4

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed]  : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20230123.1

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[failed]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20230123.2

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20230123.2

**Pull request merged**
