### PR TITLE
Suppress x-envoy headers and cluster header being sent to the backend service

### PR DESCRIPTION
**Pull request by NomadXD**
### Purpose
Prevent x-envoy headers `x-envoy-original-path` and `x-envoy-expected-rq-timeout-ms` being sent to the backend
### Issues

Fixes https://github.com/wso2/product-microgateway/issues/2986

### Automation tests
 - Unit tests added: No
 - Integration tests added: Yes

### Tested environments

OS: macOS Monterey 12.4
Env (Docker/K8s): Docker 20.10.16 on Rancher Desktop 1.4.1

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by AmaliMatharaarachchi — APPROVED** [review]

**Review by pubudu538 — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE2 cluster : dev-deployment-v2 : 20220823.19

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : dev-deployment-v2 : 20220823.19

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : dev-deployment-v2 : 20220823.19

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20220823.20

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20220825.4

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20220826.3

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : stage-deployment-v2 : 20220826.3

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20220901.3

**Comment by choreo-cicd** [comment]
[failed] DataplaneE1 cluster : prod-deployment-v2 : 20220901.3

**Comment by choreo-cicd** [comment]
[succeeded] DataplaneE1 cluster : prod-deployment-v2 : 20220901.3

**Pull request merged**
