### PR TITLE
Fixing a goroutine creation for handling API events from GA .

### PR DESCRIPTION
**Pull request by ShalkiWenushika**
### Issues

Fixes: https://github.com/wso2/product-microgateway/issues/2576

### Automation tests
 - Unit tests added: Yes/No
 - Integration tests added: Yes/No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [ ] Validated respective github issues
- [ ] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by VirajSalaka — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment-v2 : 20220125.15

**Comment by choreo-cicd** [comment]
[failed] dev-deployment-v2 : 20220125.16

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment-v2 : 20220126.1

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment-v2 : 20220128.1

**Pull request merged**
