### PR TITLE
Update choreo branch before 1.0.0-beta

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Purpose

$subject
### Issues

Task

TODO: choreo branch is not fast forward now, it should be delete and re created form main later

### Automation tests
 - Unit tests added: N/A
 - Integration tests added: N/A

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [-] Validated respective github issues
- [-] Assigned milestone to the github issue(s)

### CODE REVIEW

**Comment by praminda** [comment]
Why is it not fast forward. AFAIK we didn't merge anything directly to `choreo` recently

**Comment by renuka-fernando** [comment]
> Why is it not fast forward. AFAIK we didn't merge anything directly to `choreo` recently

We merged 2 quick bug fixes directly to the choreo branch and we also merge them to the main branch. Since those are merged to main, there is not a big issue. But it is better if we re create the choreo branch later.

**Review by praminda — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] dev-deployment : 20211123.7

**Comment by choreo-cicd** [comment]
[succeeded] dev-deployment : 20211123.11

**Comment by renuka-fernando** [comment]
- [x] Tested with already existing API
- [x] Tested create new revision and Deploy
- [x] Tested create new service and invoke

**Comment by choreo-cicd** [comment]
[succeeded] stage-deployment : 20211124.2

**Comment by choreo-cicd** [comment]
[succeeded] prod-deployment : 20211124.2

**Pull request merged**
