### PR TITLE
Set backend JWT enduser from sub claim

### PR DESCRIPTION
**Pull request by renuka-fernando**
### Issues

Fixes #

### Automation tests
 - Unit tests added: No
 - Integration tests added: No

### Tested environments

Not Tested

---
#### Maintainers: Check before merge
- [x] Assigned 'Type' label
- [x] Assigned the project
- [x] Validated respective github issues
- [x] Assigned milestone to the github issue(s)

### CODE REVIEW

**Review by slahirucd7 — APPROVED** [review]

**Review by malinthaprasan — APPROVED** [review]

**Review by shanakama — APPROVED** [review]

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20240308.17

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240308.17

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : dev-deployment-v2 : 20240308.17

**Comment by choreo-cicd** [comment]
[succeeded]  : dev-deployment-v2 : 20240308.17

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20240308.18

**Comment by choreo-cicd** [comment]
[failed] Controlplane cluster : dev-deployment-v2 : 20240308.18

**Comment by choreo-cicd** [comment]
[] Controlplane cluster : dev-deployment-v2 : 20240308.21

**Comment by choreo-cicd** [comment]
[] Dataplane(EastUS) cluster : dev-deployment-v2 : 20240308.21

**Comment by choreo-cicd** [comment]
[]  : dev-deployment-v2 : 20240308.21

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[canceled] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[failed] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded]  : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : stage-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(NorthEU) cluster : prod-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded]  : prod-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Controlplane cluster : prod-deployment-v2 : 20240308.3

**Comment by choreo-cicd** [comment]
[succeeded] Dataplane(EastUS) cluster : prod-deployment-v2 : 20240308.3

**Pull request merged**
